Library/urls.py
from django.contrib import admin
from django.urls import include, path

from Library import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='main')),
    path('user/', include('login.urls', namespace='user')),
    path('comments/', include('comments.urls', namespace='comments')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic import TemplateView

from app import views

app_name = 'app'

urlpatterns = [
    path('', views.indexpage, name='index'),
    path('author/', views.authorpage, name='author'),
    path('books/', views.bookspage, name='books'),
    path('books/<slug:genre_slug>', views.bookspage, name='books_slug'),
    path('book/<int:book_id>/', views.bookpage, name='book'),
    path('book/<int:book_id>/pdf/', views.book_pdf, name='book_pdf'),
    path('author/<int:author_id>/', views.authoprofrpage, name='author_page'),
]

login/urls.py
from django.urls import path

from login import views

app_name = 'login'

urlpatterns = [
    path('login/', views.loginpage, name='login'),
    path('reg/', views.regpage, name='reg'),
    path('profile/', views.profilepage, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('add_to_favorite/', views.add_to_favorite, name='add_to_favorite'),
    path('del_favorite/', views.del_favorite, name='del_favorite'),
]

login/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    image = models.ImageField(upload_to='user_image', blank=True, null=True)
    
    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'
        
    def __str__(self):
        return self.username

login/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from login.models import User

class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        
class UserRegForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
        )
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()
    
class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('image', 'username')
    
    image = forms.ImageField(required=False)
    username = forms.CharField()
    

login/views.py
import os
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.contrib import auth, messages
from django.urls import reverse
from django.db.models import Prefetch
from app.models import Book, FavoriteBook
from django.views.decorators.http import require_POST
 
from login.forms import ProfileForm, UserLoginForm, UserRegForm
from django.contrib.auth.decorators import login_required


from login.forms import UserLoginForm
from login.models import User

# Create your views here.
def loginpage(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            
            if user:
                auth.login(request,user)
                messages.success(request, f'{username}, Вы вошли в аккаунт')
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()
    context = {
        'form' : form
    }
    return render(request, 'login.html', context)

def regpage(request):
    if request.method == 'POST':
        form = UserRegForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('login:login'))
    else:
        form = UserRegForm()
        
    context = {
        'form': form
    }
    return render(request, 'reg.html', context)

@login_required
def profilepage(request):
    
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('login:profile'))
    else:
        form = ProfileForm(instance=request.user)
    
    favorite_books = FavoriteBook.objects.filter(user=request.user)
    
    context = {
        'form': form,
        'favorite_books': favorite_books
    }
    return render(request, 'profile.html', context)

@require_POST
def add_to_favorite(request):
    book_id = request.POST.get('book_id')
    book = Book.objects.get(id=book_id)
    user = request.user
    
    if not FavoriteBook.objects.filter(user=user, book=book).exists():
        FavoriteBook.objects.create(user=user, book=book)
        
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@require_POST
def del_favorite(request):
    book_id = request.POST.get('book_id')
    book = Book.objects.get(id=book_id)
    user = request.user
    
    favorite_book = FavoriteBook.objects.filter(user=user, book=book)
    
    if favorite_book.exists():
        favorite_book.delete()
        
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def logout(request):
    messages.success(request, 'Вы вышли из аккаунта')
    auth.logout(request)
    
    return redirect(reverse('main:index'))

login/templates/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="main">

    <h1>Login</h1>

    <form action="{% url "user:login" %}" method="POST" class="login_form">
        {% csrf_token %}
        <label for="id_username" class="login_label">Имя пользователя:</label>
        <input type="text" name="username" name="username" id="id_username" class="login" required>

        <label for="id_password" class="login_label">Пароль:</label>
        <input type="password" name="password" name="password" id="id_password" class="login" required>

        <button type="submit" class="login_b">Войти</button>
        <a href="#" class="login_a">Востановать пароль</a>
    </form>

</div>
{% endblock %}

login/templates/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="main">

    <div class="prof">
        <div class="block_image">
            {% if user.image %}
                <img src="{{ user.image.url }}" alt="Аватар" class="prof_img">
            {% else %}
                <img src="{% static '/image/123.jpg' %}" alt="Аватар" class="prof_img">
            {% endif %}
        </div>

        <div class="prof_user">
            <h2>{{ user.username }} 
                <button class="primary" onclick="window.dialog.showModal();">
                    <img src="{% static '/image/pen.png' %}" alt="Редактировать профиль" class="cheange_b">
                </button>
                <dialog id="dialog">
                    <h2>Изменить профиль:</h2>
                    {% if user.image %}
                        <img src="{{ user.image.url }}" alt="Аватар" class="prof_img">
                    {% else %}
                        <img src="{% static '/image/123.jpg' %}" alt="" class="prof_img">
                    {% endif %}

                    <form action="{% url "login:profile" %}" method="post" class="change_form" enctype="multipart/form-data">
                        {% csrf_token %}
                        <label for="id_image" class="change_text">Поменять аватар:</label>
                        <input type="file" name="image" id="id_image" placeholder="Сменить аватар:"
                        accept="image/*"><br/>
                        {% if form.image.errors %}
                            {{form.image.errors}}
                        {% endif %}

                        <label for="id_username" class="change_text">Поменять логин:</label>
                        <input type="text" name="username" id="id_username" placeholder="Сменить имя пользователя:"
                        value="{{ user.username }}">
                        {% if form.username.errors %}
                            {{form.username.errors}}
                        {% endif %}

                        <button type="submit" class="login_b">Изменить</button>
                    </form>

                    <button onclick="window.dialog.close();" aria-label="close" class="x">❌</button>
                </dialog>
            </h2>
            <p>Дата регистрации: {{ user.date_joined }}</p>
        </div>
    </div>
    <h2 class="selected_book">Избранные книги:</h2>
    <div class="init_book">
        
        {% for favorite in favorite_books %}
        <div class="favorite_book">
            <form action="{% url 'login:del_favorite' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="book_id" id="id_books_id" value="{{ favorite.book.id }}">
                <button type="submit">X</button>
            </form>
            <a href="{% url 'main:book' favorite.book.id %}" class="book_a">
                <img src="{{ favorite.book.image.url }}" alt="img" class="book_img" alt="{{ book.title }}">
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

login/templates/reg.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="main">

    <h1>Registration</h1>

    <form action="{% url "login:reg" %}" method="POST" class="login_form">
        {% csrf_token %}
        <label for="id_username" class="login_label">Имя пользователя:</label>
        <input type="text" name="username" id="id_username" class="login">
        {% if form.username.errors %}
            <p style="color:red">{{form.username.errors}}</p>
        {% endif %}

        <label for="id_email" class="login_label">Email:</label>
        <input type="mail" name="email" id="id_email" class="login">
        {% if form.email.errors %}
            <p style="color:red">{{form.email.errors}}</p>
        {% endif %}

        <label for="id_password1" class="login_label">Пароль:</label>
        <input type="password" name="password1" id="id_password1" class="login">
        {% if form.password1.errors %}
            {{form.password1.errors}}
        {% endif %}

        <label for="id_password2" class="login_label">Повторите пароль:</label>
        <input type="password" name="password2" id="id_password2" class="login">
        {% if form.password2.errors %}
            {{form.password2.errors}}
        {% endif %}

        <button type="submit" class="login_b">Регистрация</button>
    </form>

</div>
{% endblock %}