Library/urls.py
from django.contrib import admin
from django.urls import include, path

from Library import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='main')),
    path('user/', include('login.urls', namespace='user')),
    path('comments/', include('comments.urls', namespace='comments')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic import TemplateView

from app import views

app_name = 'app'

urlpatterns = [
    path('', views.indexpage, name='index'),
    path('author/', views.authorpage, name='author'),
    path('books/', views.bookspage, name='books'),
    path('books/<slug:genre_slug>', views.bookspage, name='books_slug'),
    path('book/<int:book_id>/', views.bookpage, name='book'),
    path('book/<int:book_id>/pdf/', views.book_pdf, name='book_pdf'),
    path('author/<int:author_id>/', views.authoprofrpage, name='author_page'),
]

login/urls.py
from django.urls import path

from login import views

app_name = 'login'

urlpatterns = [
    path('login/', views.loginpage, name='login'),
    path('reg/', views.regpage, name='reg'),
    path('profile/', views.profilepage, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('add_to_favorite/', views.add_to_favorite, name='add_to_favorite'),
    path('del_favorite/', views.del_favorite, name='del_favorite'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "/style.css" %}">
    <link rel="stylesheet" href="{% static "/login.css" %}">
    <link rel="icon" type="image/png" sizes="32x32" href='{% static "image/book_icon.png" %}'>
    <title>Library</title>
</head>
<body>
    <header>
        <div class="logo"><a href="{% url "main:index" %}">Library</a></div>

        <div class="meny">
            <a href="{% url "main:index" %}" class="meny_title">Главная</a>
            <a href="{% url "main:books" %}" class="meny_title">Книги</a>
            <a href="{% url "main:author" %}" class="meny_title">Авторы</a>
            <div class="meny_autho">
                {% if not user.is_authenticated %}
                <div>
                    <button class="meny_butt"><a href="{% url "login:login" %}">Войти</a></button>
                </div>
                <div>
                    <button class="meny_butt"><a href="{% url "login:reg" %}">Регистрация</a></button>
                </div>
                {% else %}
                    {% if user.is_staff or user.is_admin %}
                    <div>
                        <button class="meny_butt"><a href="{% url "admin:index" %}">Админка</a></button>
                    </div>
                    {% endif %}
                <div>
                    <button class="meny_butt"><a href="{% url "login:profile" %}">Профиль</a></button>
                </div>
                <div>
                    <button class="meny_butt_logout"><a href="{% url "login:logout" %}">Выйти</a></button>
                </div>
                    
                {% endif %}
            </div>
        </div>
    </header>

{% block content %}

{% endblock %}
</body>
</html>