Library/urls.py
from django.contrib import admin
from django.urls import include, path

from Library import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='main')),
    path('user/', include('login.urls', namespace='user')),
    path('comments/', include('comments.urls', namespace='comments')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic import TemplateView

from app import views

app_name = 'app'

urlpatterns = [
    path('', views.indexpage, name='index'),
    path('author/', views.authorpage, name='author'),
    path('books/', views.bookspage, name='books'),
    path('books/<slug:genre_slug>', views.bookspage, name='books_slug'),
    path('book/<int:book_id>/', views.bookpage, name='book'),
    path('book/<int:book_id>/pdf/', views.book_pdf, name='book_pdf'),
    path('author/<int:author_id>/', views.authoprofrpage, name='author_page'),
]

comments/urls.py
from django.urls import path

from comments import views

app_name = 'comments'

urlpatterns = [
    path('del_com/', views.del_com, name='del_com'),
]

login/urls.py
from django.urls import path

from login import views

app_name = 'login'

urlpatterns = [
    path('login/', views.loginpage, name='login'),
    path('reg/', views.regpage, name='reg'),
    path('profile/', views.profilepage, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('add_to_favorite/', views.add_to_favorite, name='add_to_favorite'),
    path('del_favorite/', views.del_favorite, name='del_favorite'),
]

app/templates/authors.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="main">
        <h1>Authors</h1>

        <div class="authors">
            {% for author in authors %}
            <div class="author">
            <a href="{% url "main:author_page" author.id %}" class="author_a">
                <img src="{{ author.image.url }}" alt="img" class="author_img">
            </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/books.html
{% extends "base.html" %}
{% load static %}

{% load books_tags %}

{% block content %}
    <div class="content">
        <div class="filter_blok">
            <h2>Filters:</h2>
            <b>По Жанрам:</b>
            <div class="filter">
                {% for genre in genres %}
                    <a href="{% url "main:books_slug" genre.slug %}" class="filter_a"><p class="filter_p">{{ genre.name }}</p></a>
                {% endfor %}
            </div>
            <p>-----------------------</p>
            <form action='{% url "main:books" %}' method='get'>
                <p><input type="radio" name="order_by" id="" value="title" 
                    {% if request.GET.order_by == 'title' %}checked{% endif %}><b>По алфавиту</b></p>
                <input type="radio" name="order_by" id="" value="popular" 
                    {% if request.GET.order_by == 'popular' %}checked{% endif %}><b>По популярности</b>
                <p><input type="radio" name="order_by" id="" value="-rating" 
                    {% if request.GET.order_by == '-rating' %}checked{% endif %}><b>По рейтенгу</b></p>
                <button type="submit" class="all_book_in_genre">Поиск</button>
            </form>
        </div>
        <div class="main">
            <h1>Books</h1>
            <h2>{{ genres.name }}</h2>
            <div class="books">
                {% for book in books %}
                <div class="book">
                    <a href="{% url 'main:book' book.id %}" class="book_a">
                        <img src="{{ book.image.url }}" alt="img" class="book_img" alt="{{ book.title }}">
                    </a>
                </div>
                {% endfor %}
        </div>
        <div class="container">
            <ul class="pagination">
                <li>
                    <a class="{% if not books.has_previous %}disabled{% endif %}" href="{% if books.has_previous %}
                        ?{% change_params page=previous_page_number %}
                    {% else %}
                        #
                    {% endif %} 
                    ">Prev</a>
                </li>
                {% for page in books.paginator.page_range %}
                {% if page >= books.number|add:-2 and page <= books.number|add:2 %}
                    <li class="{% if books.number == page %}active{% endif %}">
                        <a href="?{% change_params page=page %}">{{ page }}</a>
                    </li>
                {% endif %}
                {% endfor %}
                <li>
                    <a class="{% if not books.has_next %}disabled{% endif %}" href="{% if books.has_next %}
                        ?{% change_params page=next_page_number %}
                    {% else %}
                        #
                    {% endif %} 
                    ">Next</a>
                </li>
            </ul>
          </div>
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="main">
        <h1>Library</h1>

        <h2 class="text_book">Бестселлеры: 
            <a href="{% url "main:books_slug" 'bestsellery' %}"><button class="all_book_in_genre">Все книги жанра</button></a>
        </h2>
        <div class="books">
            {% for book in bestsellery %}
            <div class="book">
                <a href="{% url 'main:book' book.id %}" class="book_a">
                    <img src="{{ book.image.url }}" alt="img" class="book_img" alt="{{ book.title }}">
                </a>
            </div>
            {% endfor %}
            
        </div>
        <h2 class="text_book">Романы: 
            <a href="{% url "main:books_slug" 'romany' %}"><button class="all_book_in_genre">Все книги жанра</button></a>
        </h2>
        <div class="books">
            {% for book in romany %}
            <div class="book">
                <a href="{% url 'main:book' book.id %}" class="book_a">
                    <img src="{{ book.image.url }}" alt="img" class="book_img" alt="{{ book.title }}">
                </a>
            </div>
            {% endfor %}
            
        </div>
        <a href="{% url "main:books" %} " class="genre_b"><button class="all_genre">Все жанры</button></a>
    </div>
{% endblock %}

app/templates/page_author.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="main">
        <div class="img_author">
            <div class="">
                <img src="{{ author.image.url }}" alt="img" class="img">
            </div>
        </div>
        <h2 class="text_name">{{ author.firs_name }} {{ author.last_name }}</h2>
        <p class="text_bio">{{ author.bio }}</p>

        <div class="text_book">Все книги автора:</div>
        <div class="books">
            {% for book in books %}
            <div class="book">
                <a href="{% url "main:book" book.id %}" class="book_a">
                    <img src="{{ book.image.url }}" alt="img" class="book_img">
                    <p>{{ book.tile }}</p>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/page_book.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="main_books">
        <div class="book">
            <a href="page_book.html" class="">
                <img src="{{ books.image.url }}" alt="img" class="book_img">
            </a>
        </div>

        <div class="text">
            <h2 class="text_title"> {{ books.title }}
                {% if request.user.is_authenticated %}
                <form action="{% url 'login:add_to_favorite' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="book_id" id="id_books_id" value="{{ books.id }}">
                    <button type="submit">Добавить в избранное</button>
                </form>
                {% endif %}
            </h2>
            <a href="{% url "main:author_page" books.id_author.id %}" class="author_a_in_book">{{ books.id_author.firs_name }} {{ books.id_author.last_name }}</a>
            <p class="genre">Жанр: {% for genre in books.genres.all %}
                {{ genre }}
            {% endfor %}</p>
            
            <p class="text_p">{{ books.description }}</p>
            <p>Рейтинг книги: 
                {% for i in rating|get_range %}
                    <img src="{% static "/image/star_op.png" %}" alt="" class="star">
                {% endfor %}
                {{ books.rating }}</p>
            <a href="{% url 'main:book_pdf' books.id %}" target="_blank" class="btn btn-primary"><button class="read">Читать книгу</button></a>
        </div>
</div>       
        <div class="reviews">
            <h2 class="review_title">Оставить отзыв:</h2>
            <form action="{% url "main:book" books.id %}" method="POST" class="reviews_form">
                {% csrf_token %}
                Рейтинг: 
                <div class="rating-area">
                    <input type="radio" id="star-5" name="rating" value="5">
                    <label for="star-5" title="Оценка «5»"></label>	
                    <input type="radio" id="star-4" name="rating" value="4">
                    <label for="star-4" title="Оценка «4»"></label>    
                    <input type="radio" id="star-3" name="rating" value="3">
                    <label for="star-3" title="Оценка «3»"></label>  
                    <input type="radio" id="star-2" name="rating" value="2">
                    <label for="star-2" title="Оценка «2»"></label>    
                    <input type="radio" id="star-1" name="rating" value="1">
                    <label for="star-1" title="Оценка «1»"></label>
                </div>
                <label for="">Отзыв:</label>
                <input type="text" name="comment" id="id_comment" cols="30" rows="10"></input>
                <button type="submit" {% if not request.user.is_authenticated %}disabled{% endif %}>Отправить</button>
                {% if not request.user.is_authenticated %}<p style="color: red; opacity:50%">*Авторизируйтесь чтобы оставить отзыв</p>{% endif %}
            </form>
            <div class="reviews_users">
                <h2 class="review_title">Отзывы:</h2>
                {% for comment in comments %}
                <div class="review_user">
                    <div class="review_user_block">
                        <img src="{{ comment.user.image.url }}" alt="" class="review_img_user">
                        <p class="username">{{ comment.user.username }}</p>
                        <p class="data">{{ comment.data }}</p>
                    </div>
                    
                    {% for i in comment.rating|get_range  %}
                        <img src="{% static "/image/star_op.png" %}" alt="" class="star">
                    {% endfor %}
                    <p class="text_review">{{ comment.text }}</p>
                    {% if request.user.id == comment.user.id %}
                    <form action="{% url 'comments:del_com' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="comment_id" id="id_comment_id" value="{{ comment.id }}">
                        <button type="submit">Удалить комментарий</button>'
                    </form>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </div>

{% endblock %}